<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>SuzerainModdingKit</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>SuzerainModdingKit</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\Unity.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>$(GamePath)/MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
			<HintPath>$(GamePath)/MelonLoader\net6\MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GamePath)/MelonLoader\net6\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>$(GamePath)/MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="StoryFragments\Bill\AddBillOptions.cs" />
		<Compile Include="StoryFragments\AddStoryFragmentOptions.cs" />
		<Compile Include="Character\CharacterNameSelector.cs" />
		<Compile Include="Character\CharacterSelector.cs" />
		<Compile Include="DebugOverlay.cs" />
		<Compile Include="Journal\CustomJournalEntryData.cs" />
		<Compile Include="Journal\JournalManager.cs" />
		<Compile Include="Core.cs" />
		<Compile Include="Events.cs" />
		<Compile Include="GameFlowPatches.cs" />
		<Compile Include="GameState.cs" />
		<Compile Include="Journal\Patches.cs" />
		<Compile Include="Report\CustomReportData.cs" />
		<Compile Include="Save\Patches.cs" />
		<Compile Include="Save\SaveManager.cs" />
		<Compile Include="SmkInfo.cs" />
		<Compile Include="StoryFragments\Bill\Patches.cs" />
		<Compile Include="StoryFragments\Conversation\ConversationInjection.cs" />
		<Compile Include="StoryFragments\Conversation\ConversationInjector.cs" />
		<Compile Include="StoryFragments\Conversation\ConversationNode.cs" />
		<Compile Include="StoryFragments\Conversation\ConversationNodeHook.cs" />
		<Compile Include="StoryFragments\Conversation\CustomConversationFragment.cs" />
		<Compile Include="StoryFragments\Conversation\InjectedConversationNode.cs" />
		<Compile Include="StoryFragments\Conversation\NodeSelectors\ConversationNodeModdedNameSelector.cs" />
		<Compile Include="StoryFragments\Conversation\NodeSelectors\ConversationNodeArticyIDSelector.cs" />
		<Compile Include="StoryFragments\Conversation\NodeSelectors\ConversationNodeSelector.cs" />
		<Compile Include="StoryFragments\Conversation\ConversationRegistry.cs" />
		<Compile Include="StoryFragments\Conversation\NodeSelectors\ConversationStartNodeSelector.cs" />
		<Compile Include="StoryFragments\Conversation\Patches.cs" />
		<Compile Include="StoryFragments\Conversation\ResolvedConversationNodeHook.cs" />
		<Compile Include="StoryFragments\Bill\CustomBillFragment.cs" />
		<Compile Include="StoryFragments\CustomStoryFragmentData.cs" />
		<Compile Include="StoryFragments\Decision\CustomDecisionFragment.cs" />
		<Compile Include="StoryFragments\Decision\DecisionManager.cs" />
		<Compile Include="StoryFragments\Decision\DecisionOptionInfo.cs" />
		<Compile Include="StoryFragments\Decision\Patches.cs" />
		<Compile Include="StoryPack\StoryPackInfo.cs" />
		<Compile Include="Utils\ArticyIDGenerator.cs" />
		<Compile Include="Utils\ConversationNodeSequenceBuilder.cs" />
		<Compile Include="Utils\DialogueUtils.cs" />
		<Compile Include="Utils\Il2CppUtils.cs" />
		<Compile Include="VanillaData\SuzerainStoryPackInfo.cs" />
		<Compile Include="VanillaData\SuzerainTokenName.cs" />
		<Compile Include="VanillaData\SuzerainCharacterName.cs" />
		<Compile Include="Variables.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Meziantou.Analyzer" Version="3.0.29">
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	    <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(GamePath)/Mods&quot;" />
	</Target>
</Project>
